[package]
name = "zarrs_jpeg"
version = "0.1.0"
edition = "2024"

[dependencies]
inventory = "0.3.24"
jpeg-encoder = "0.7.0"
log = "0.4.33"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
zarrs = { version = "0.23.13", default-features = false }
zune-jpeg = "0.5.15"

[features]
async = ["zarrs/async"]

[profile.dev.package.zune-jpeg]
opt-level = 3

[dev-dependencies]
png = "0.18.1"
zarrs = { version = "0.23.13", default-features = false, features = [
    "filesystem",
] }
